[package]
name = "lavalink"
version = "0.1.0"
authors = ["sponges <spongybacon@hotmail.co.uk>"]

[dependencies]
websocket = "0.20.2"
tokio-core = "0.1"
futures = "0.1"
serde = "1.0.11"
serde_json = "1.0.2"